name: Daily contributions
run-name: 📅 Scheduled run for daily contributions
on:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  daily-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and
        uses: actions/checkout@v3
      - name: Update 'Last updated' date
        run: |
          sed -i -e '$s/.*/'"<\!-- Last updated: $(date '+%c') \-->"'/' ${{ github.workspace }}/README.md
      - name: Commit changes
        run: |
          git config --global user.name '${{ github.repository_owner }}'
          git config --global user.email '${{ github.repository_owner }}@users.noreply.github.com'
          git commit -am "Scheduled commit: update last modified date"
          git push origin master
